### ISSUE TITLE
Null byte in string when updating repository configuration

### ISSUE THREAD

**Issue by s0undt3ch** [ericpaulbishop/redmine_git_hosting#127]
```
Fethcing changes for /tmp/redmine_git_hosting/gitolite-admin
Our hook is already installed
Fethcing changes for /tmp/redmine_git_hosting/gitolite-admin
Our hook is already installed
Setting up hooks for project xpto

ArgumentError (string contains null byte):
  vendor/bundle/ruby/1.8/gems/activesupport-2.3.14/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'
  vendor/bundle/ruby/1.8/gems/activesupport-2.3.14/lib/active_support/core_ext/kernel/agnostics.rb:7:in ``'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/base.rb:1333:in `send'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/base.rb:1333:in `perform_action_without_filters'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/filters.rb:617:in `call_filters'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/flash.rb:151:in `perform_action'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/base.rb:532:in `send'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/base.rb:532:in `process_without_filters'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/filters.rb:606:in `process'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/base.rb:391:in `process'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/base.rb:386:in `call'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/routing/route_set.rb:438:in `call'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/dispatcher.rb:87:in `dispatch'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/dispatcher.rb:121:in `_call'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/dispatcher.rb:130:in `build_middleware_stack'
  vendor/bundle/ruby/1.8/gems/activerecord-2.3.14/lib/active_record/query_cache.rb:29:in `call'
  vendor/bundle/ruby/1.8/gems/activerecord-2.3.14/lib/active_record/query_cache.rb:29:in `call'
  vendor/bundle/ruby/1.8/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
  vendor/bundle/ruby/1.8/gems/activerecord-2.3.14/lib/active_record/query_cache.rb:9:in `cache'
  vendor/bundle/ruby/1.8/gems/activerecord-2.3.14/lib/active_record/query_cache.rb:28:in `call'
  vendor/bundle/ruby/1.8/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/string_coercion.rb:25:in `call'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/params_parser.rb:15:in `call'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/session/cookie_store.rb:99:in `call'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/failsafe.rb:26:in `call'
  vendor/bundle/ruby/1.8/gems/actionpack-2.3.14/lib/action_controller/dispatcher.rb:106:in `call'
  vendor/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/connection.rb:84:in `pre_process'
  vendor/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/connection.rb:82:in `catch'
  vendor/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/connection.rb:82:in `pre_process'
  vendor/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/connection.rb:57:in `process'
  vendor/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/connection.rb:42:in `receive_data'
  vendor/bundle/ruby/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
  vendor/bundle/ruby/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
  vendor/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/backends/base.rb:61:in `start'
  vendor/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/server.rb:159:in `start'
  vendor/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/controllers/controller.rb:86:in `start'
  vendor/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/runner.rb:185:in `send'
  vendor/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/runner.rb:185:in `run_command'
  vendor/bundle/ruby/1.8/gems/thin-1.2.11/lib/thin/runner.rb:151:in `run!'
  vendor/bundle/ruby/1.8/gems/thin-1.2.11/bin/thin:6
  vendor/bundle/ruby/1.8/bin/thin:19:in `load'
  vendor/bundle/ruby/1.8/bin/thin:19

Rendering /srv/chili/public/500.html (500 Internal Server Error)
```

**Comment by s0undt3ch** [comment]
As it is now I can't update any repository configurations.

**Comment by s0undt3ch** [comment]
This seems to be from older hook keys. How can we regenerate the hook keys for every repository?

**Comment by s0undt3ch** [comment]
The issue was with the hook keys. Had to delete them all and regenerate. Seems all good now.
