### ISSUE TITLE
Repositories not created

### ISSUE THREAD

**Issue by kstripp** [ericpaulbishop/redmine_git_hosting#152]
I am attempting to install and configure redmine_git_hosting on my 1.3stable redmine installation,
but I seem to be unable to create repositories.  Creation directly through gitolite (clone, update files, push) works fine, but the only results I get from the plugin is the following error message:

<pre>
Processing RepositoriesController#edit (for 68.42.79.139 at 2012-02-09 02:21:58) [POST]
  Parameters: {"commit"=>"Create", "action"=>"edit", "authenticity_token"=>"V6dhIsF+dX/bNVuljD6flEBAU3/HzKCLIQ3UBx92ZYM=", "id"=>"ufo", "controller"=>"repositories", "extra"=>{"git_http"=>"0", "git_daemon"=>"0", "notify_cia"=>"0"}, "repository_scm"=>"Git"}
  [4;35;1mSQL (0.7ms)[0m   [0mSELECT max(`settings`.updated_on) AS max_updated_on FROM `settings` [0m
  [4;36;1mUser Load (0.5ms)[0m   [0;1mSELECT * FROM `users` WHERE (`users`.`id` = 3) AND (users.status = 1) AND ( (`users`.`type` = 'User' OR `users`.`type` = 'AnonymousUser' ) ) [0m
  [4;35;1mProject Load (0.7ms)[0m   [0mSELECT * FROM `projects` WHERE (`projects`.`identifier` = 'ufo') LIMIT 1[0m
  [4;36;1mEnabledModule Load (0.5ms)[0m   [0;1mSELECT name FROM `enabled_modules` WHERE (`enabled_modules`.project_id = 9) [0m
  [4;35;1mRepository Load (0.5ms)[0m   [0mSELECT * FROM `repositories` WHERE (`repositories`.project_id = 9) LIMIT 1[0m
  [4;36;1mSQL (0.4ms)[0m   [0;1mBEGIN[0m
  [4;35;1mGitRepositoryExtra Create (0.6ms)[0m   [0mINSERT INTO `git_repository_extras` (`git_http`, `git_daemon`, `repository_id`, `notify_cia`, `key`) VALUES(1, 1, NULL, 0, 'TPJTBHNSQHIHRBYGDHYXYLAWSJSBVFSBEEDJTAFLLRVNVTRDTIFYYYGPTJBKUERQJXQIWTYKPIOOMLVTVOKFJXEYEEFUXVKLDJUVFUFCNTTTVHLR')[0m
  [4;36;1mSQL (3.3ms)[0m   [0;1mCOMMIT[0m

NoMethodError (undefined method `each' for nil:NilClass):
  /usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:92:in `process_request'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:418:in `start_request_handler'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:358:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/utils.rb:184:in `safe_fork'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:354:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:163:in `start'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:213:in `start'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
  /usr/lib/phusion_passenger/passenger-spawn-server:61

Rendering /usr/share/redmine/public/500.html (500 Internal Server Error)
</pre>

Any ideas what might be generating this?  I'd appreciate any help or suggestions.

**Comment by kubitron** [comment]
This version of the plugin is known not to be compatible with Redmine 1.3.

You should try my version to see if it works better for you (it works fine on 1.3 as far as I know).  Use the master branch.

https://github.com/kubitron/redmine_git_hosting

**Comment by kstripp** [comment]
Huh... I could have sworn I tried that already and got the same error as before.  But this time I got a different result:
Redmine acts as though the plugin isn't even there when looking at repository settings, and gives an internal error (500) when I try going to the plugin settings.

The log shows this:

<pre>
Creating bin directory: /usr/share/redmine/vendor/plugins/redmine_git_hosting/bin, Owner www-data
***> Cannot create bin directory: /usr/share/redmine/vendor/plugins/redmine_git_hosting/bin
</pre>


This smells like a permissions issue to me, but unfortunately I don't have time to debug any more tonight.

**Comment by kstripp** [comment]
Ok, so I couldn't resist checking one more thing before calling it quits for the night.

Changed ownership of vendor/plugins/redmine_git_hosting to www-data, and the error in my last post went away.
But now I am back to my first error.
