### ISSUE TITLE
Problem with plugin installation

### ISSUE THREAD

**Issue by fvezzoli** [ericpaulbishop/redmine_git_hosting#160]
Hi, I use this plugin with chiliproject 2.0, now I install another istance and I install the plugin with the istruction in the Readme file, after, when i go to configure page in the admin, i get this error:

Errno::ENOENT in Settings#plugin

Showing vendor/plugins/redmine_git_hosting/app/views/settings/_redmine_git_hosting.html.erb where line #91 raised:

No such file or directory - gitTmpDir/redmine_git_hosting/redmine_git_hosting_lock
Extracted source (around line #91):

88: 
89:     <p>
90:         <label><%= l(:label_hook_installed)%></label>
91:         <%= image_tag((GitHosting.check_hooks_installed==true ? 'true.png' : 'exclamation.png'), :style => "vertical-align:bottom;") %>
92:         <em><%= (GitHosting.check_hooks_installed==true ? '' : GitHosting.check_hooks_installed) %></em>
93:         <br />
94:     </p>
Trace of template inclusion: app/views/settings/plugin.rhtml

RAILS_ROOT: /var/www/chiliproject

Application Trace | Framework Trace | Full Trace
/var/www/chiliproject/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:272:in `initialize'
/var/www/chiliproject/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:272:in`new'
/var/www/chiliproject/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:272:in `lock'
/var/www/chiliproject/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:494:in`check_hooks_installed'
/var/www/chiliproject/vendor/plugins/redmine_git_hosting/app/views/settings/_redmine_git_hosting.html.erb:91:in `_run_erb_vendor47plugins47redmine_git_hosting47app47views47settings47_redmine_git_hosting46html46erb_locals_object_redmine_git_hosting_settings'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/renderable.rb:34:in`send'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/renderable.rb:34:in `render'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/base.rb:306:in`with_template'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/renderable.rb:30:in `render'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/renderable_partial.rb:20:in`render'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/benchmarking.rb:30:in `benchmark'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/renderable_partial.rb:19:in`render'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/template.rb:205:in `render_template'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/renderable_partial.rb:44:in`render_partial'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/partials.rb:184:in `render_partial'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/base.rb:267:in`render'
/var/www/chiliproject/app/views/settings/plugin.rhtml:6:in `_run_rhtml_app47views47settings47plugin46rhtml'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/helpers/capture_helper.rb:36:in`call'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/helpers/capture_helper.rb:36:in `capture'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/helpers/capture_helper.rb:129:in`with_output_buffer'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/helpers/capture_helper.rb:36:in `capture'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/helpers/form_tag_helper.rb:469:in`form_tag_in_block'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/helpers/form_tag_helper.rb:39:in `form_tag'
/var/www/chiliproject/app/views/settings/plugin.rhtml:4:in`_run_rhtml_app47views47settings47plugin46rhtml'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/renderable.rb:34:in `send'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/renderable.rb:34:in`render'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/base.rb:306:in `with_template'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/renderable.rb:30:in`render'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/template.rb:205:in `render_template'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/base.rb:265:in`render'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/base.rb:348:in `_render_with_layout'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_view/base.rb:262:in`render'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/base.rb:1252:in `render_for_file'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/base.rb:936:in`render_without_benchmark'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/benchmarking.rb:51:in `render'
/usr/local/lib64/ruby/gems/1.8/gems/activesupport-2.3.14/lib/active_support/core_ext/benchmark.rb:17:in`ms'
/usr/lib64/ruby/1.8/benchmark.rb:308:in `realtime'
/usr/local/lib64/ruby/gems/1.8/gems/activesupport-2.3.14/lib/active_support/core_ext/benchmark.rb:17:in`ms'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/benchmarking.rb:51:in `render'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/base.rb:1328:in`default_render'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/base.rb:1334:in `perform_action_without_filters'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/filters.rb:617:in`call_filters'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/filters.rb:610:in `perform_action_without_benchmark'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
/usr/local/lib64/ruby/gems/1.8/gems/activesupport-2.3.14/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/lib64/ruby/1.8/benchmark.rb:308:in`realtime'
/usr/local/lib64/ruby/gems/1.8/gems/activesupport-2.3.14/lib/active_support/core_ext/benchmark.rb:17:in `ms'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/benchmarking.rb:68:in`perform_action_without_rescue'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/rescue.rb:160:in `perform_action_without_flash'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/flash.rb:151:in`perform_action'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/base.rb:532:in `send'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/base.rb:532:in`process_without_filters'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/filters.rb:606:in `process'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/base.rb:391:in`process'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/base.rb:386:in `call'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/routing/route_set.rb:438:in`call'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/dispatcher.rb:87:in `dispatch'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/dispatcher.rb:121:in`_call'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/dispatcher.rb:130:in `build_middleware_stack'
/usr/local/lib64/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/query_cache.rb:29:in`call'
/usr/local/lib64/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/query_cache.rb:29:in `call'
/usr/local/lib64/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/query_cache.rb:34:in`cache'
/usr/local/lib64/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/query_cache.rb:9:in `cache'
/usr/local/lib64/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/query_cache.rb:28:in`call'
/usr/local/lib64/ruby/gems/1.8/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/string_coercion.rb:25:in`call'
/usr/local/lib64/ruby/gems/1.8/gems/rack-1.1.3/lib/rack/head.rb:9:in `call'
/usr/local/lib64/ruby/gems/1.8/gems/rack-1.1.3/lib/rack/methodoverride.rb:24:in`call'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/params_parser.rb:15:in `call'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/session/cookie_store.rb:99:in`call'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/failsafe.rb:26:in `call'
/usr/local/lib64/ruby/gems/1.8/gems/rack-1.1.3/lib/rack/lock.rb:11:in`call'
/usr/local/lib64/ruby/gems/1.8/gems/rack-1.1.3/lib/rack/lock.rb:11:in `synchronize'
/usr/local/lib64/ruby/gems/1.8/gems/rack-1.1.3/lib/rack/lock.rb:11:in`call'
/usr/local/lib64/ruby/gems/1.8/gems/actionpack-2.3.14/lib/action_controller/dispatcher.rb:106:in `call'
/usr/lib64/ruby/gems/1.8/gems/thin-1.3.1/lib/rack/adapter/rails.rb:69:in`call'
/usr/lib64/ruby/gems/1.8/gems/thin-1.3.1/lib/thin/connection.rb:80:in `pre_process'
/usr/lib64/ruby/gems/1.8/gems/thin-1.3.1/lib/thin/connection.rb:78:in`catch'
/usr/lib64/ruby/gems/1.8/gems/thin-1.3.1/lib/thin/connection.rb:78:in `pre_process'
/usr/lib64/ruby/gems/1.8/gems/thin-1.3.1/lib/thin/connection.rb:53:in`process'
/usr/lib64/ruby/gems/1.8/gems/thin-1.3.1/lib/thin/connection.rb:38:in `receive_data'
/usr/lib64/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in`run_machine'
/usr/lib64/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
/usr/lib64/ruby/gems/1.8/gems/thin-1.3.1/lib/thin/backends/base.rb:61:in`start'
/usr/lib64/ruby/gems/1.8/gems/thin-1.3.1/lib/thin/server.rb:159:in `start'
/usr/lib64/ruby/gems/1.8/gems/thin-1.3.1/lib/thin/controllers/controller.rb:86:in`start'
/usr/lib64/ruby/gems/1.8/gems/thin-1.3.1/lib/thin/runner.rb:185:in `send'
/usr/lib64/ruby/gems/1.8/gems/thin-1.3.1/lib/thin/runner.rb:185:in`run_command'
/usr/lib64/ruby/gems/1.8/gems/thin-1.3.1/lib/thin/runner.rb:151:in `run!'
/usr/lib64/ruby/gems/1.8/gems/thin-1.3.1/bin/thin:6
/usr/bin/thin:8:in`load'
/usr/bin/thin:8
Request

Parameters:

{"id"=>"redmine_git_hosting"}
Show session dump

Response

Headers:

{"Cache-Control"=>"no-cache",
 "Content-Type"=>"text/html"}

Anyone have idea of the error?

**Comment by fvezzoli** [comment]
I had forget to install the gem required by plugin
