### ISSUE TITLE
TypeError (can't convert nil into String)

### ISSUE THREAD

**Issue by s0undt3ch** [ericpaulbishop/redmine_git_hosting#28]
TypeError (can't convert nil into String)

```
Processing ProjectsController#create (for 89.154.180.246 at 2011-07-12 10:48:29) [POST]
  Parameters: {"commit"=>"Save", "action"=>"create", "authenticity_token"=>"IzqZKzECxLg6ptLJt79kTOzE/P2oc8T7AD0MRK91PHo=", "project"=>{"issue_custom_field_ids"=>[""], "name"=>"teste", "tracker_ids"=>["4", "2", "3", "1", ""], "homepage"=>"", "parent_id"=>"54", "is_public"=>"0", "description"=>"", "identifier"=>"teste", "enabled_module_names"=>["repository", ""]}, "controller"=>"projects"}
Redirected to http://dev.ufsoft.org/projects/teste/settings

TypeError (can't convert nil into String):
  vendor/plugins/redmine_git_hosting/app/models/git_hosting_observer.rb:34:in `update_repositories'
  vendor/plugins/redmine_git_hosting/app/models/git_hosting_observer.rb:7:in `after_create'
  /usr/lib/ruby/1.8/active_record/observer.rb:171:in `send'
  /usr/lib/ruby/1.8/active_record/observer.rb:171:in `update'
  /usr/lib/ruby/1.8/observer.rb:185:in `notify_observers'
  /usr/lib/ruby/1.8/observer.rb:184:in `each'
  /usr/lib/ruby/1.8/observer.rb:184:in `notify_observers'
  /usr/lib/ruby/1.8/active_record/callbacks.rb:357:in `notify'
  /usr/lib/ruby/1.8/active_record/callbacks.rb:350:in `callback'
  /usr/lib/ruby/1.8/active_record/callbacks.rb:267:in `create'
  /usr/lib/ruby/1.8/active_record/base.rb:2927:in `create_or_update_without_callbacks'
  /usr/lib/ruby/1.8/active_record/callbacks.rb:250:in `create_or_update'
  /usr/lib/ruby/1.8/active_record/base.rb:2577:in `save_without_validation'
  /usr/lib/ruby/1.8/active_record/validations.rb:1090:in `save_without_dirty'
  /usr/lib/ruby/1.8/active_record/dirty.rb:79:in `save_without_transactions'
  /usr/lib/ruby/1.8/active_record/transactions.rb:229:in `send'
  /usr/lib/ruby/1.8/active_record/transactions.rb:229:in `with_transaction_returning_status'
  /usr/lib/ruby/1.8/active_record/connection_adapters/abstract/database_statements.rb:136:in `transaction'
  /usr/lib/ruby/1.8/active_record/transactions.rb:182:in `transaction'
  /usr/lib/ruby/1.8/active_record/transactions.rb:228:in `with_transaction_returning_status'
  /usr/lib/ruby/1.8/active_record/transactions.rb:196:in `save'
  /usr/lib/ruby/1.8/active_record/transactions.rb:208:in `rollback_active_record_state!'
  /usr/lib/ruby/1.8/active_record/transactions.rb:196:in `save'
  /usr/lib/ruby/1.8/active_record/associations/has_one_association.rb:64:in `replace'
  /usr/lib/ruby/1.8/active_record/associations.rb:1287:in `repository='
  /usr/lib/ruby/1.8/active_support/callbacks.rb:178:in `send'
  /usr/lib/ruby/1.8/active_support/callbacks.rb:178:in `evaluate_method'
  /usr/lib/ruby/1.8/active_support/callbacks.rb:166:in `call'
  /usr/lib/ruby/1.8/action_controller/filters.rb:662:in `run_after_filters'
  /usr/lib/ruby/1.8/action_controller/filters.rb:619:in `call_filters'
  /usr/lib/ruby/1.8/action_controller/filters.rb:610:in `perform_action_without_benchmark'
  /usr/lib/ruby/1.8/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
  /usr/lib/ruby/1.8/action_controller/benchmarking.rb:68:in `perform_action_without_rescue'
  /usr/lib/ruby/1.8/action_controller/rescue.rb:160:in `perform_action_without_flash'
  /usr/lib/ruby/1.8/action_controller/flash.rb:151:in `perform_action'
  /usr/lib/ruby/1.8/action_controller/base.rb:532:in `send'
  /usr/lib/ruby/1.8/action_controller/base.rb:532:in `process_without_filters'
  /usr/lib/ruby/1.8/action_controller/filters.rb:606:in `process'
  /usr/lib/ruby/1.8/action_controller/base.rb:391:in `process'
  /usr/lib/ruby/1.8/action_controller/base.rb:386:in `call'
  /usr/lib/ruby/1.8/action_controller/routing/route_set.rb:438:in `call'
  /usr/lib/ruby/1.8/action_controller/dispatcher.rb:87:in `dispatch'
  /usr/lib/ruby/1.8/action_controller/dispatcher.rb:121:in `_call'
  /usr/lib/ruby/1.8/action_controller/dispatcher.rb:130:in `build_middleware_stack'
  /usr/lib/ruby/1.8/active_record/query_cache.rb:29:in `call'
  /usr/lib/ruby/1.8/active_record/query_cache.rb:29:in `call'
  /usr/lib/ruby/1.8/active_record/connection_adapters/abstract/query_cache.rb:34:in `cache'
  /usr/lib/ruby/1.8/active_record/query_cache.rb:9:in `cache'
  /usr/lib/ruby/1.8/active_record/query_cache.rb:28:in `call'
  /usr/lib/ruby/1.8/active_record/connection_adapters/abstract/connection_pool.rb:361:in `call'
  /usr/lib/ruby/1.8/action_controller/string_coercion.rb:25:in `call'
  /usr/lib/ruby/1.8/action_controller/params_parser.rb:15:in `call'
  /usr/lib/ruby/1.8/action_controller/session/cookie_store.rb:99:in `call'
  /usr/lib/ruby/1.8/action_controller/failsafe.rb:26:in `call'
  /usr/lib/ruby/1.8/action_controller/dispatcher.rb:106:in `call'
  thin (1.2.11) lib/thin/connection.rb:84:in `pre_process'
  thin (1.2.11) lib/thin/connection.rb:82:in `catch'
  thin (1.2.11) lib/thin/connection.rb:82:in `pre_process'
  thin (1.2.11) lib/thin/connection.rb:57:in `process'
  thin (1.2.11) lib/thin/connection.rb:42:in `receive_data'
  eventmachine (0.12.10) lib/eventmachine.rb:256:in `run_machine'
  eventmachine (0.12.10) lib/eventmachine.rb:256:in `run'
  thin (1.2.11) lib/thin/backends/base.rb:61:in `start'
  thin (1.2.11) lib/thin/server.rb:159:in `start'
  thin (1.2.11) lib/thin/controllers/controller.rb:86:in `start'
  thin (1.2.11) lib/thin/runner.rb:185:in `send'
  thin (1.2.11) lib/thin/runner.rb:185:in `run_command'
  thin (1.2.11) lib/thin/runner.rb:151:in `run!'
  thin (1.2.11) bin/thin:6
  /var/lib/gems/1.8/bin/thin:19:in `load'
  /var/lib/gems/1.8/bin/thin:19

Rendering /srv/chili/public/500.html (500 Internal Server Error)


Processing WelcomeController#robots (for 66.249.71.138 at 2011-07-12 10:49:36) [GET]
  Parameters: {"action"=>"robots", "controller"=>"welcome"}
Rendering welcome/robots
Completed in 59ms (View: 4, DB: 2) | 200 OK [http://dev.ufsoft.org/robots.txt]
```

This is using current master.

**Comment by s0undt3ch** [comment]
Some more info about my install, ChiliProject 1.5.0:

```
$ RAILS_ENV=production script/about
About your application's environment
Ruby version              1.8.7 (x86_64-linux)
RubyGems version          1.3.5
Rack version              1.1
Rails version             2.3.11
Active Record version     2.3.11
Active Resource version   2.3.11
Action Mailer version     2.3.11
Active Support version    2.3.11
Edge Rails revision       unknown
Application root          /srv/chili
Environment               production
Database adapter          postgresql
Database schema version   20110218202110

About your Redmine plugins
Redmine Gitolite Hook plugin           0.1.1
Redmine Git Hosting Plugin             0.1.1
Project removal plugin                 0.0.1
reCAPTCHA for user self registration   0.1.0
Redmine Tags                           0.1.0
Redmine OpenID Selector plugin         0.0.1
Mylyn Connector plugin                 2.7.2.stable
Google AdSense                         0.0.1
Code View Configuration Plugin         1.0.0
reStructuredText formatter             0.0.1
Google Analytics plugin                0.2.0
```

**Comment by s0undt3ch** [comment]
The above issue seems to disappear if /tmp/redmine_git_hosting/gitolite-admin is cloned.

Also:

```
>> Listening on /srv/chili/tmp/sockets/thin.0.socket, CTRL+C to stop
remote: 
remote:                 ***** WARNING *****        
remote:         the following users (pubkey files in parens) do not appear in the config file:        
remote: redmine_s0undt3ch_1309769709_133184(redmine_s0undt3ch_1309769709_133184.pub)        
To git@dev.ufsoft.org:gitolite-admin.git
   abf43b1..dd8e17b  master -> master
fatal: /usr/lib/git-core/git-pull cannot be used without a working tree.
remote: creating deluge/teste...        
remote: Initialized empty Git repository in /srv/vcs-repositories/repos-git/deluge/teste.git/        
remote: 
remote:                 ***** WARNING *****        
remote:         the following users (pubkey files in parens) do not appear in the config file:        
remote: redmine_s0undt3ch_1309769709_133184(redmine_s0undt3ch_1309769709_133184.pub)        
To git@dev.ufsoft.org:gitolite-admin.git
   dd8e17b..d01c89c  master -> master
/srv/chili/vendor/rails/railties/lib/commands/runner.rb:48: (eval):1: compile error (SyntaxError)
(eval):1: unterminated string meets end of file
        from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `eval'
        from /srv/chili/vendor/rails/railties/lib/commands/runner.rb:48
        from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `require'
        from /srv/chili/script/runner:3
fatal: /usr/lib/git-core/git-pull cannot be used without a working tree.
remote: 
remote:                 ***** WARNING *****        
remote:         the following users (pubkey files in parens) do not appear in the config file:        
remote: redmine_s0undt3ch_1309769709_133184(redmine_s0undt3ch_1309769709_133184.pub)        
To git@dev.ufsoft.org:gitolite-admin.git
   d01c89c..afc079e  master -> master
```

Don't mind the key issue, the other error is what I'm trying to address your attention to.

**Comment by ohthehugemanatee** [comment]
Is there anything else that might be using your gitolite-admin repo?  I think the plugin never refreshes it's cache of gitolite-admin.git, it just assumes that it's the only committer.

**Comment by s0undt3ch** [comment]
Closing this, the checked out plugin was a mix from my hook repo and your master

**Comment by s0undt3ch** [comment]
Just saw your post now. I think I had made a change to the repo on my laptop and commited it.

Should the plugin assume it's the single entity commiting to it? Anyway, not that problematic.
