### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by ohthehugemanatee** [ericpaulbishop/redmine_git_hosting#41]
I'm having trouble with this plugin crashing redmine entirely.  I get this information out of Phusion's error page, or on the terminal if I run rake db:migrate :

```
example** Invoke db:migrate_plugins (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
undefined method `[]' for nil:NilClass
/usr/local/ruby/lib/ruby/gems/1.8/gems/actionpack-2.3.12/lib/action_controller/routing/builder.rb:159:in `build'
/usr/local/ruby/lib/ruby/gems/1.8/gems/actionpack-2.3.12/lib/action_controller/routing/route_set.rb:310:in `add_route'
/usr/local/ruby/lib/ruby/gems/1.8/gems/actionpack-2.3.12/lib/action_controller/routing/route_set.rb:19:in `connect'
/srv/www/projects.example.com/chili/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:77:in `add_route_for_project_with_map'
/srv/www/projects.example.com/chili/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:69:in `add_route_for_project'
/usr/local/ruby/lib/ruby/gems/1.8/gems/actionpack-2.3.12/lib/action_controller/routing/route_set.rb:227:in `draw'
/srv/www/projects.example.com/chili/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:68:in `add_route_for_project'
/srv/www/projects.example.com/chili/vendor/plugins/redmine_git_hosting/config/routes.rb:3
/srv/www/projects.example.com/chili/vendor/plugins/redmine_git_hosting/config/routes.rb:2:in `each'
/srv/www/projects.example.com/chili/vendor/plugins/redmine_git_hosting/config/routes.rb:2
/usr/local/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.12/lib/active_support/dependencies.rb:173:in `load_without_new_constant_marking'
/usr/local/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.12/lib/active_support/dependencies.rb:173:in `load'
/usr/local/ruby/lib/ruby/gems/1.8/gems/actionpack-2.3.12/lib/action_controller/routing/route_set.rb:287:in `load_routes!'
/usr/local/ruby/lib/ruby/gems/1.8/gems/actionpack-2.3.12/lib/action_controller/routing/route_set.rb:287:in `each'
/usr/local/ruby/lib/ruby/gems/1.8/gems/actionpack-2.3.12/lib/action_controller/routing/route_set.rb:287:in `load_routes!'
/usr/local/ruby/lib/ruby/gems/1.8/gems/actionpack-2.3.12/lib/action_controller/routing/route_set.rb:267:in `reload!'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rails-2.3.12/lib/initializer.rb:537:in `initialize_routing'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rails-2.3.12/lib/initializer.rb:188:in `process'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rails-2.3.12/lib/initializer.rb:113:in `send'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rails-2.3.12/lib/initializer.rb:113:in `run'
/srv/www/projects.example.com/chili/config/environment.rb:33
/usr/local/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.12/lib/active_support/dependencies.rb:182:in `require'
/usr/local/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.12/lib/active_support/dependencies.rb:182:in `require'
/usr/local/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.12/lib/active_support/dependencies.rb:547:in `new_constants_in'
/usr/local/ruby/lib/ruby/gems/1.8/gems/activesupport-2.3.12/lib/active_support/dependencies.rb:182:in `require'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rails-2.3.12/lib/tasks/misc.rake:4
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:205:in `call'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:205:in `execute'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:200:in `each'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:200:in `execute'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:158:in `invoke_with_call_chain'
/usr/local/ruby/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:176:in `invoke_prerequisites'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:174:in `each'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:174:in `invoke_prerequisites'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:157:in `invoke_with_call_chain'
/usr/local/ruby/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:151:in `invoke_with_call_chain'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/task.rb:144:in `invoke'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:112:in `invoke_task'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in `top_level'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in `each'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:90:in `top_level'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:84:in `top_level'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:62:in `run'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:129:in `standard_exception_handling'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/lib/rake/application.rb:59:in `run'
/usr/local/ruby/lib/ruby/gems/1.8/gems/rake-0.9.2/bin/rake:32
/usr/bin/rake:19:in `load'
/usr/bin/rake:19
Tasks: TOP => db:migrate_plugins => environment
```

I tried deleting all lines from the repositories table where the repo type is specified as Repository::Git (most of them are just "Git"). That gets me access to the basic chiliproject interface again, so long as I don't try to visit a repo-related page.  But of course I still get the error on db:migrate or db:migrate plugins.

**Comment by ericpaulbishop** [comment]
I am having trouble reproducing this error -- it works fine for my.  I notice you were able to catch the created_on bug (which I just fixed) which is a bit more subtle and implies you got this working, so I'm wondering if you managed to figure out what was going on here.

**Comment by ohthehugemanatee** [comment]
Yeah, it's bizarre.  You can see a more or less full log of my efforts to get things working in https://github.com/ericpaulbishop/redmine_git_hosting/issues/27 .  I started getting this error shortly after my last comment there.  At first I thought it was an out of memory condition, since I was running on an Amazon Micro instance.  So I set up an Amazon "Small" (1.5gb ram IIRC) on Ubuntu, and used your yourchili scripts to set things up there.  I copied over the database directly from the Micro instance, and got the same error.  That's how I figured it was in the database.

Eventually I decided this might be because of the different repo creation methods I'd used; like perhaps with the redmine_git_hosting patch, it didn't know what to do with repos of type "Git", or something like that. So on a whim I tried just deleting all the entries from the "repositories" table, and everything worked perfectly.  If I add a repo for a project, of course the repo is already there in the right place, so with a quick " ruby script/runner "Repository.fetch_changesets" -e production" I get my commit history back.  Since I only have 5 or 6 projects, it was easy to do this manual re-creation process. 

So my conclusion is that this error is from some sort of corruption in the Repositories table.  If it helps, I can give you a dump of the problematic DB, or just a printout of the 5 or so rows that were in that table.  I suspect it will be immediately obvious to you what is wrong "by inspection."

But there might be an even bigger opportunity here.  I'm happy to give you direct shell access to the Micro instance that I worked with in the ticket above.  It's a great playground for us to figure out the issues with the module on CentOS, not to mention a typical "other person's assumptions" installation.  Thoughts?  How can I help nail this issue for posterity?

**Comment by christophlsa** [comment]
I got the same error:

```
# RAILS_ENV=production rake db:migrate_plugins --trace
(in /opt/redmine)
** Invoke db:migrate_plugins (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
undefined method `[]' for nil:NilClass
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/builder.rb:159:in `build'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:310:in `add_route'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:19:in `connect'
/opt/redmine/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:92:in `add_route_for_project_with_map'
/opt/redmine/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:84:in `add_route_for_project'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:227:in `draw'
/opt/redmine/vendor/plugins/redmine_git_hosting/lib/git_hosting.rb:83:in `add_route_for_project'
/opt/redmine/vendor/plugins/redmine_git_hosting/config/routes.rb:3
/opt/redmine/vendor/plugins/redmine_git_hosting/config/routes.rb:2:in `each'
/opt/redmine/vendor/plugins/redmine_git_hosting/config/routes.rb:2
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:173:in `load_without_new_constant_marking'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:173:in `load'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:287:in `load_routes!'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:287:in `each'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:287:in `load_routes!'
/usr/lib/ruby/gems/1.8/gems/actionpack-2.3.11/lib/action_controller/routing/route_set.rb:267:in `reload!'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:537:in `initialize_routing'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:188:in `process'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:113:in `send'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/initializer.rb:113:in `run'
/opt/redmine/config/environment.rb:20
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
/usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:547:in `new_constants_in'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.11/lib/active_support/dependencies.rb:182:in `require'
/usr/lib/ruby/gems/1.8/gems/rails-2.3.11/lib/tasks/misc.rake:4
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:607:in `invoke_prerequisites'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in `invoke_prerequisites'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:596:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in `load'
/usr/bin/rake:19
```

**Comment by christophlsa** [comment]
ah, I removed all existing repositories from redmine (as mentioned in ticket #51) and now it works. :)
