### ISSUE TITLE
Not migrating correctly

### ISSUE THREAD

**Issue by TheEmpty** [ericpaulbishop/redmine_git_hosting#6]
PHPMyAdmin view: http://i52.tinypic.com/sfuque.png
What I did: migrated database to new server

[www@el-abid rails_app]$ rake db:migrate:plugins RAILS_ENV=production
(in /home/www/redmine.el-abid.com/rails_app)
Migrating plugin redmine_git_hosting ...
Migrating plugin redmine_knowledgebase ...

[www@el-abid rails_app]$ ruby script/server -e production
=> Booting WEBrick
=> Rails 2.3.11 application starting on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
[2011-05-09 22:55:59] INFO  WEBrick 1.3.1
[2011-05-09 22:55:59] INFO  ruby 1.8.7 (2011-02-18) [x86_64-linux]
[2011-05-09 22:55:59] INFO  WEBrick::HTTPServer#start: pid=9705 port=3000

Processing MyController#account (for 69.120.49.100 at 2011-05-09 22:56:00) [GET]
  Parameters: {"action"=>"account", "controller"=>"my"}
Rendering template within layouts/base
Rendering my/account

ActionView::TemplateError (Mysql::Error: Table 'redmine.gitolite_public_keys' doesn't exist: SELECT \* FROM `gitolite_public_keys` WHERE (active=1) AND (`gitolite_public_keys`.user_id = 1)  ORDER BY active DESC, created_at DESC) on line #44 of vendor/plugins/redmine_git_hosting/app/views/my/account.rhtml:
41: </div>
42:
43: <div class="splitcontentright">
44:     <% @gitolite_public_keys = @user.gitolite_public_keys.all(:order => 'active DESC, created_at DESC', :conditions => "active=1") %>
45:     <table class="list">
46:             <tr>
47:                     <% if @gitolite_public_keys.any? %>

```
vendor/plugins/redmine_git_hosting/app/views/my/account.rhtml:44:in `_run_rhtml_vendor47plugins47redmine_git_hosting47app47views47my47account46rhtml'
/usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
/usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
/usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:173:in `start_thread'
/usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:162:in `start'
/usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:162:in `start_thread'
/usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:95:in `start'
/usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:92:in `each'
/usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:92:in `start'
/usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:23:in `start'
/usr/local/rvm/rubies/ruby-1.8.7-p334/lib/ruby/1.8/webrick/server.rb:82:in `start'
```

Rendering /home/www/redmine.el-abid.com/rails_app/public/500.html (500 Internal Server Error)

**Comment by TheEmpty** [comment]
Here is what I did to fix it: http://pastebin.com/Vez0giKa

This is might be more of a redmine error then the plugin, I'm unaware of how redmine knows what migrations to run.
