### ISSUE TITLE
_repository.rhtml error

### ISSUE THREAD

**Issue by czechbox** [ericpaulbishop/redmine_git_hosting#68]
Just loaded the latest and got this....

ActionView::TemplateError (undefined method `+' for nil:NilClass) on line #14 of vendor/plugins/redmine_git_hosting/app/views/projects/settings/_repository.rhtml:
11:  
12:             <% if @repository && @repository.is_a?(Repository::Git) %>
13:                 <%
14:                     mirror_pubkey = GitHosting.mirror_push_public_key
15:                     extra_vals = { :git_daemon=>"1", :git_http=>"1", :notify_cia=>"0" }
16:                     extra_vals.each_key do |e|
17:                         begin

```
vendor/plugins/redmine_git_hosting/app/views/projects/settings/_repository.rhtml:14:in `_run_rhtml_vendor47plugins47redmine_git_hosting47app47views47projects47settings47_repository46rhtml_locals_object_repository'
vendor/plugins/redmine_git_hosting/app/views/projects/settings/_repository.rhtml:1:in `_run_rhtml_vendor47plugins47redmine_git_hosting47app47views47projects47settings47_repository46rhtml_locals_object_repository'
passenger (3.0.8) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
passenger (3.0.8) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
passenger (3.0.8) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
passenger (3.0.8) lib/phusion_passenger/utils.rb:479:in `safe_fork'
passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:180:in `start'
passenger (3.0.8) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
passenger (3.0.8) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
passenger (3.0.8) lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
passenger (3.0.8) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
passenger (3.0.8) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
passenger (3.0.8) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
passenger (3.0.8) helper-scripts/passenger-spawn-server:99
```

Rendering /opt/redmine-1.2/public/500.html (500 Internal Server Error)

**Comment by ericpaulbishop** [comment]
You probably didn't install the public key that is associated with the gitolite-admin private key, which is now required in v0.4.0.  This is noted in the new instructions (though admittedly not highlighted).

**Comment by ericpaulbishop** [comment]
I just committed a fix that should prevent you from seeing this error even if the public key isn't properly installed -- you just won't have a proper display of the key necessary for pushing to repo mirrors in this case.

**Comment by czechbox** [comment]
erm... actually, i did have the key installed

**Comment by ericpaulbishop** [comment]
Well, there's something wrong with your public key -- it's bombing out on the exact line where it's loading the public key.  Maybe it's a permissions issue?
