### ISSUE TITLE
Internal error when adding public key to profile

### ISSUE THREAD

**Issue by sboisson** [ericpaulbishop/redmine_git_hosting#94]
(running on Chiliproject/2.2.0 - Passenger/3.0.9 - nginx/1.0.6 - CentOS/5.6-x86_64)

Here is what I get in the logs.

<pre>
Processing GitolitePublicKeysController#create (for X.X.X.X at 2011-09-28 18:47:09) [POST]
  Parameters: {"public_key"=>{"title"=>"sboisson", "key"=>"ssh-rsa AAAA(...)n.local\r\n"}, "commit"=>"Créer", "action"=>"create", "authenticity_token"=>"nntBxT(...)z+rQ=", "controller"=>"gitolite_public_keys"}
Cloning gitolite-admin repository
Our hook is already installed

Errno::ENOENT (No such file or directory - /tmp/redmine_git_hosting/gitolite-admin/conf/gitolite.conf):
  vendor/plugins/redmine_git_hosting/app/models/git_hosting_observer.rb:78:in `update_repositories'
  vendor/plugins/redmine_git_hosting/app/models/git_hosting_observer.rb:39:in `after_create'
  /usr/local/rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/observer.rb:185:in `notify_observers'
  /usr/local/rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/observer.rb:184:in `each'
  /usr/local/rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/observer.rb:184:in `notify_observers'
  vendor/plugins/redmine_git_hosting/app/controllers/gitolite_public_keys_controller.rb:29:in `create'
  passenger (3.0.9) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
  passenger (3.0.9) lib/phusion_passenger/abstract_request_handler.rb:513:in `accept_and_process_next_request'
  passenger (3.0.9) lib/phusion_passenger/abstract_request_handler.rb:274:in `main_loop'
  passenger (3.0.9) lib/phusion_passenger/classic_rails/application_spawner.rb:321:in `start_request_handler'
  passenger (3.0.9) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `send'
  passenger (3.0.9) lib/phusion_passenger/classic_rails/application_spawner.rb:275:in `handle_spawn_application'
  passenger (3.0.9) lib/phusion_passenger/utils.rb:479:in `safe_fork'
  passenger (3.0.9) lib/phusion_passenger/classic_rails/application_spawner.rb:270:in `handle_spawn_application'
  passenger (3.0.9) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
  passenger (3.0.9) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.9) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.9) lib/phusion_passenger/abstract_server.rb:180:in `start'
  passenger (3.0.9) lib/phusion_passenger/classic_rails/application_spawner.rb:149:in `start'
  passenger (3.0.9) lib/phusion_passenger/spawn_manager.rb:219:in `spawn_rails_application'
  passenger (3.0.9) lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
  passenger (3.0.9) lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
  passenger (3.0.9) lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
  passenger (3.0.9) lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  passenger (3.0.9) lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
  passenger (3.0.9) lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
  passenger (3.0.9) lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
  passenger (3.0.9) lib/phusion_passenger/abstract_server.rb:357:in `__send__'
  passenger (3.0.9) lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
  passenger (3.0.9) lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
  passenger (3.0.9) helper-scripts/passenger-spawn-server:99

Rendering /vol/data/projects/chiliproject/public/500.html (500 Internal Server Error)
</pre>

**Comment by sboisson** [comment]
My bad, the path to gitolite admin keys were wrong..
Closing..
